#!/bin/bash

#############################################################
# Help                                                      #
#############################################################

Help()
{
  # Display help
  printf "\nbash POD\n  Runs a bash of the specified pod\n"
  printf "\npods\n  Get pods\n"
  printf "\nfind_pod TERM\n  Search for pods that matches a term\n\n"
  echo "-h" 
  echo "  Get help"
  printf "\nfind TYPE TERM\n  Search for object of an specific type that matches a term; e.g. find pod my_pod\n\n"
}

bash() {
  local POD_ID=$1
  if [ -z $POD_ID ]
  then
    echo "Error: You must specify a POD id."
    Help
    exit 1
  fi
    
  printf "[%s] Running: %s bash\n" "$(date)" "$POD_ID"
  kubectl exec -it $POD_ID -- bash
}

pods() {
  printf "[%s] Getting pods...\n" "$(date)" 
  kubectl get pods
}

# I think I should change this in the future
find() {
  local TO_FIND=$1
  case $TO_FIND in
    "pod") # Search a pod by a term
      find_pod $2
      exit;;
     "*") 
       echo "Error: Invalid option."
       Help
       exit 2;;
  esac
  echo "finding"
}
find_pod() {
  local TERM=$1
  printf "[%s] Results for \"%s\":\n" "$(date)" "$TERM" 
  kubectl get pods | grep $TERM
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################
############################################################
# Process the input options. Add options as needed.        #
############################################################
#Get options
case "$1" in
    "") exit;;
    "-h") # Get help
      Help
      exit;;
    bash) # Runs a container bash
      "$@"
      exit;;
    pods) # Get pods
      "$@"
      exit;;
    find) # find
      "$@"
      exit;;
   find_pod) # Search for pods that matches a term
      "$@"
      exit;;
    *) # Invalid option
      echo "Error: Invalid option. Use -h to get help"
      exit 2;;
esac
